name: Build Nektar Windows

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Clone Nektar from GitLab
      run: |
        git clone --recursive https://gitlab.nektar.info/nektar/nektar.git .
        # Мы скачиваем всё в текущую папку сервера

    - name: Install Dependencies via vcpkg
      run: |
        vcpkg install boost-python:x64-windows
        vcpkg install tinyxml:x64-windows

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        # Указываем путь к vcpkg, чтобы CMake нашел библиотеки
        cmake -G "Visual Studio 17 2022" -A x64 `
              -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" `
              -DNEKTAR_BUILD_PYTHON=ON `
              -DNEKTAR_BUILD_UTILITIES=ON `
              -DCMAKE_INSTALL_PREFIX=./dist ..

    - name: Build and Install
      run: |
        cd build
        cmake --build . --config Release -j 4
        cmake --install . --config Release --prefix ../final_package

    - name: Upload Result
      uses: actions/upload-artifact@v4
      with:
        name: Nektar-Windows-Package
        path: final_package/
        if-no-files-found: error
