name: Build Nektar Windows

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Clone Nektar from GitLab
      run: |
        # Клонируем основной репозиторий без автоматических субмодулей
        git clone https://gitlab.nektar.info/nektar/nektar.git .
        # Обновляем субмодули вручную, игнорируя ошибки (чтобы битый tutorial не вешал билд)
        git submodule update --init --recursive || true

    - name: Install Dependencies via vcpkg
      run: |
        vcpkg install boost-python:x64-windows
        vcpkg install tinyxml:x64-windows

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 `
              -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" `
              -DNEKTAR_BUILD_PYTHON=ON `
              -DNEKTAR_BUILD_UTILITIES=ON `
              -DNEKTAR_BUILD_SOLVERS=ON `
              -DNEKTAR_BUILD_THIRDPARTY_LIBS=ON `
              -DCMAKE_INSTALL_PREFIX=./dist ..

    - name: Build
      run: |
        cd build
        cmake --build . --config Release -j 4

    - name: Create Installer (.exe)
      run: |
        cd build
        # Команда CPack создаст один установочный файл на основе собранного проекта
        cpack -G NSIS -C Release

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: Nektar-Setup-EXE
        path: build/*.exe
